version: "3.9"

services:
  python:
    container_name: population-analysis
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/app
    ports:
      - 8888:8888
    entrypoint: /bin/bash
